[package]
name = "tensor"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "23.0.0"
bytemuck = "1.19.0"
futures = "0.3.31"
futures-intrusive = "0.5.0"
once_cell = "1.20.2"
# Tokio is only required for testing
# tokio = { version = "1", features = ["full"] }
